Add Button component package and storybook stories
EightShapes/esds-library pull request #133
Opened 2020-09-23 01:35 UTC by kevinmpowell

View examples on storybook here: https://5f6a4995f949220022193194-zulwjvcnbp.chromatic.com

I didn't fully flesh out button states since the figma file didn't seem to have them fully fleshed out (they seem super subtle). I only did default and hover.

I also didn't fully exercise all permutations (yet). Waiting on a bug in chromatic to get resolved, then I'm gonna hit it with a really big sink and find the upper limit of screenshot sizes.

API code is here: https://github.com/EightShapes/esds-library/blob/feature/button/components/esds-button/src/EsdsButton.js#L20

2020-09-23 13:02 UTC, nathanacurtis commented on components/esds-button/documentation/esds-button-docs.json
> +          "name": "type",
What's the default? Are the defaults the first `type`, conventionally? If so, that's not clear here.

2020-09-23 13:07 UTC, nathanacurtis requested changes

2020-09-23 13:07 UTC, nathanacurtis commented on components/esds-button/documentation/esds-button-docs.json
> +          "description": "visual style of the button",
The description here seems wrong, and descriptions in general seem not polished enough to reflect good editorial quality in a demo.

2020-09-23 13:07 UTC, nathanacurtis commented on components/esds-button/documentation/esds-button-docs.json
> +          "name": "",
Why does button have a slot? I cannot imagine why we'd allow that.

2020-09-23 13:07 UTC, nathanacurtis commented on components/esds-button/src/EsdsButton.js
> +      /*
The spacing of comments makes it hard to know if the comment applies to the prop before or after the comment. Could we add space or some other contrast to make that connection clearer?

2020-09-23 13:07 UTC, nathanacurtis commented on components/esds-button/src/esds-button.scss
> +  background: $esds-color-interactive-default-on-light;
I'm leaning increasingly towards changing our language from `interactive` to `action`. If you agree, let's do so now everywhere.

2020-09-23 13:07 UTC, nathanacurtis commented on components/esds-button/src/esds-button.scss
> +  .esds-button--small & {
This needs to be mixinized now separated from button for all font sizes. I object to having responsive sizing of standard type sizes within single components.

2020-09-23 19:36 UTC, nathanacurtis commented on components/esds-button/src/esds-button.scss
> +  background: $esds-button-color-background-secondary-default;
Aren't we using this `secondary` color in other components? Should we promote this from component to global, likely in the `color-action` set?

2020-09-23 19:37 UTC, nathanacurtis commented on components/esds-button/src/esds-button.scss
> +  background: $esds-button-color-background-secondary-default;
Ignore this. I needed a screenshot of a comment to update my Tokens deck ;)

2020-09-25 19:27 UTC, kevinmpowell commented on components/esds-button/documentation/esds-button-docs.json
> +          "name": "type",
No that was a miss, default type is `button`

2020-09-25 19:29 UTC, kevinmpowell commented on components/esds-button/documentation/esds-button-docs.json
> +          "description": "visual style of the button",
Yes, this was a copy/paste error. I'm not inclined to polish button descriptions editorially since I don't know yet if they'll be shown in the demo.

2020-09-25 19:32 UTC, kevinmpowell commented on components/esds-button/documentation/esds-button-docs.json
> +          "name": "",
! Really? Every web component button I've built has three slots: default, left icon and right icon. It's so you can do this:

```
<esds-button>Hello World</esds-button>
```
Which is a better syntax analog to the HTML button vs: 
```
<esds-button text="Hello World"></esds-button>
```

For icon slots it's so entire icon components can be passed in:
```
<esds-button>
  Hello World
  <esds-icon slot="icon-left" size="small" title="aria-specific thing for this one icon" name="house"></esds-icon>
</esds-button>
```

2020-09-25 19:33 UTC, kevinmpowell commented on components/esds-button/src/EsdsButton.js
> +      /*
Agreed, I've added a space to separate them.

2020-09-25 19:34 UTC, kevinmpowell commented on components/esds-button/src/esds-button.scss
> +  .esds-button--small & {
Not sure I follow. Are you saying:

`esds-font-size('body-m', responsive)`
vs.
`esds-font-size('body-m', fixed)`

?

2020-09-25 19:35 UTC, kevinmpowell commented on components/esds-button/src/esds-button.scss
> +  background: $esds-button-color-background-secondary-default;
cute

2020-09-25 19:44 UTC, kevinmpowell commented on components/esds-button/src/esds-button.scss
> +  background: $esds-color-interactive-default-on-light;
agreed. Swapped `interactive` for `action`

2020-09-25 19:57 UTC, nathanacurtis commented on components/esds-button/documentation/esds-button-docs.json
> +          "name": "",
Word up. Thanks for the reminder.

2020-09-25 19:58 UTC, nathanacurtis commented on components/esds-button/src/esds-button.scss
> +  .esds-button--small & {
Yes.

2020-10-01 13:41 UTC, merged